### ISSUE TITLE
Glitchy behavior associated with one client making a large number of requests

### ISSUE THREAD

**Issue by jeffkaufman** [gwillen/solstice-audio-test#131]
On echo.jefftk.com around 1608771113 something weird happened:

```
/api
/api?read_clock=77221013441719&n_samples=28800&userid=82049336984&reset_user_state=true&username=Pseudonym
/api?read_clock=77221013470519&n_samples=28800&userid=82049336984&username=Pseudonym
/api?read_clock=77221013499319&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013528119&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013556919&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013588599&n_samples=31680&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013617399&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api
/api?read_clock=77221013312018&n_samples=28800&userid=82049336984&reset_user_state=true&username=Pseudonym
/api?read_clock=77221013340818&n_samples=28800&userid=82049336984&username=Pseudonym
/api
/api?read_clock=77221013369618&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013398418&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013427218&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013456018&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013484818&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013513618&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013542418&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013571218&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013600018&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013628818&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013657618&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013686418&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013715218&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api
/api
/api?read_clock=77221013389652&n_samples=28800&userid=82049336984&reset_user_state=true&username=Pseudonym
/api?read_clock=77221013418452&n_samples=28800&userid=82049336984&username=Pseudonym
/api?read_clock=77221013447252&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013476052&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013504852&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013533652&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013562452&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013591252&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013620052&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013648852&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013677652&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013706452&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013735252&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013764052&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
/api?read_clock=77221013792852&n_samples=28800&userid=82049336984&user_summary=1&username=Pseudonym
...
```

(I replaced the user name with "Pseudonym")

You can see this with `grep 'Thu Dec 24 00:5[12]' /var/log/uwsgi-echo-02.log | grep -o '/api[^ ]*'`

Note that the occasional request does not include `user_summary=1`, which I don't think should happen?

I'm not sure what was causing it to rapidly disconnect and reconnect?

**Comment by jeffkaufman** [comment]
I wonder if maybe after getting enough kill messages from the server we should have the client deactivate itself?

**Comment by jeffkaufman** [comment]
Since my guess is the client was receiving some sort of server kill message

**Comment by jeffkaufman** [comment]
I managed to reproduce this by leaving two clients connected for a really long time, including letting my computer go to sleep in between.

One client thinks it is an offset six, the other thinks it is at offset three.

Looking at the mixing console, I'm seeing both clients rapidly counting down from their assigned number to three spaces earlier before reconnecting.

Something like:

```
[reconnect]
client1 3
client2 6

client1 2
client2 5

client1 1
client2 4

client1 0
client2 3

[reconnect]
[repeats]
```

**Comment by jeffkaufman** [comment]
Both clients are in a 10 request cycle:

![Screen Shot 2020-12-25 at 1 44 52 PM](https://user-images.githubusercontent.com/262566/103140664-6f961b80-46b7-11eb-9b86-dc3afe5b37e0.png)

**Comment by jeffkaufman** [comment]
Server is erroring:

```
Request raised exception!
Params: read_clock=77228261198822&write_clock=77228261094516&n_samples=28800&userid=69922236669&user_summary=1&username=jeff
 Traceback (most recent call last):
  File "/home/jefftk/code/solstice-audio-test/server_wrapper.py", line 320, in do_POST
    data, x_audio_metadata = handle_post(userid, n_samples, in_data_raw, query_string, client_address=client_address)
  File "/home/jefftk/code/solstice-audio-test/server_wrapper.py", line 155, in handle_post
    in_data, query_string, print_status, client_address=client_address)
  File "/home/jefftk/code/solstice-audio-test/server_wrapper.py", line 196, in handle_json_post
    raise Exception(out_json["error"] + inner_bt)
Exception: argument out of range
Backend error details: Traceback (most recent call last):
  File "/home/jefftk/code/solstice-audio-test/shm.py", line 100, in post
    out_json_raw, out_data = server.handle_json_post(in_json_raw, in_data)
  File "/home/jefftk/code/solstice-audio-test/server.py", line 660, in handle_json_post
    in_data, query_string, print_status=True, client_address=client_address)
  File "/home/jefftk/code/solstice-audio-test/server.py", line 1077, in handle_post
    bin_summary = binary_user_summary(user_summary(requested_user_summary))
  File "/home/jefftk/code/solstice-audio-test/server.py", line 539, in binary_user_summary
    delay))
struct.error: argument out of range
```

**Comment by jeffkaufman** [comment]
b5997ed fixes the server erroring, but for some reason the client is still seriously off

**Comment by jeffkaufman** [comment]
I'm seeing the client make ~9 XHRs per second

**Comment by jeffkaufman** [comment]
Instead of the expected one every 600ms

**Comment by jeffkaufman** [comment]
The client read clock just gets farther and farther ahead of the server clock. I can have a server kill the client when this happens, but it doesn't explain why it is happening

**Comment by jeffkaufman** [comment]
I think we are trying to make up too many dropped calls:

![Screen Shot 2020-12-25 at 2 04 07 PM](https://user-images.githubusercontent.com/262566/103140883-15e32080-46ba-11eb-83c4-229bd19c6085.png)

**Comment by gwillen** [comment]
This all makes sense to me, if you put the machine to sleep with the client running, it will definitely go crazy.

Fixes I think make sense:
(1) As you already did, killing clients that get into the future -- this is a "should never happen" in any event, although we may want to firm up our invariants around this -- technically a client is not _prohibited_ from asking to be at offset 0, and such a client could easily slip _slightly_ into the future by accident, but in practice we never put clients there.
(2) On the client side, if we reconnect to the server, we should stop trying to make up dropped calls at that point, and it's a bug that we don't.
(3) On the client side, if our dropped calls to make up for gets too high, we should give up and reconnect instead.

I can implement 2 and 3 -- I assume this doesn't come up hugely often, so it's not super urgent (and in particular is not wanted for Solstice 2.)
