### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by vivarose** [gwillen/solstice-audio-test#235]
First crash:
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at update_active_users (https://echo.jefftk.com/demo.js:1185:50)
    at EventTarget.<anonymous> (https://echo.jefftk.com/demo.js:1971:7)
    at EventTarget.server_metadata_received (https://echo.jefftk.com/app.js:1146:10)
    at https://echo.jefftk.com/app.js:1293:12

Then I refreshed the page and it crashed again:
TypeError: Cannot read property 'appendChild' of undefined
TypeError: Cannot read property 'appendChild' of undefined
    at RemoteAudioTrackPublication.<anonymous> (https://echo.jefftk.com/demo.js:1675:35)
    at RemoteAudioTrackPublication.emit (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:57:3991)
    at RemoteAudioTrackPublication._subscribed (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:41:17507)
    at RemoteParticipant._addTrack (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:42:26930)
    at trackSignalingSubscribed (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:42:15779)
    at RemoteTrackPublicationV2.<anonymous> (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:42:14542)
    at RemoteTrackPublicationV2.emit (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:57:4111)
    at RemoteTrackPublicationV2.setTrackTransceiver (https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:44:3154)
    at https://media.twiliocdn.com/sdk/js/video/releases/2.8.0/twilio-video.min.js:47:23531

**Comment by jimmosk** [comment]
This was just as the "bucket was finishing emptying" after successfully singing the round C-O-F-F-E-E
