### ISSUE TITLE
Issues on Linux Firefox and Chromium today

### ISSUE THREAD

**Issue by elysdir** [gwillen/solstice-audio-test#255]
Hi—I was showing the server to a friend, and they ran into a bunch of problems with it.

First, using the latest Chromium version on Linux, they tried to calibrate; it correctly generated beeps and showed the number of ms of latency in text, but then it said that it couldn’t calibrate. (I don’t have the exact error message, sorry.)

Next, using the latest Firefox on Linux, they got through calibration, and I saw their video for a couple of seconds, but then their video disappeared and they got an error message. We could still hear each other, but I couldn’t see them.

Eventually, they tried signing in as a non-singer using Firefox on Linux. That worked fine. I sang a song, they heard me, the video worked, etc. But of course I couldn’t hear them sing.

So they tried signing in again as a singer using Firefox on Linux, but turning off their video. That worked fine until I clicked Lead a Song, at which point I could no longer hear them. Their microphone was on, and we could both type in the text chat, and they could hear me, but I couldn’t hear them at all. I clicked Start and then Stop, so we were back in the non-singing area, but I still couldn’t hear them.

At that point we ran out of time. Any ideas about what might help? Is FF/Linux supported? Would restarting the server help?

…I should note that everything worked as expected on my end (Chrome/Mac) throughout. (I suppose it’s possible that the times I couldn’t hear them were problems on my end rather than theirs, but I suspect not.)

thanks,

—Jed

**Comment by elysdir** [comment]
Followup: The first error message that my friend received was this:

Error: Not allowed to start ignoring input after the clock has already started! Error: Not allowed to start ignoring input after the clock has already started! at Player.handle_message (https://echo.jefftk.com/audio-worklet.js:612:15) at https://echo.jefftk.com/audio-worklet.js:512:16 at Player.try_do (https://echo.jefftk.com/audio-worklet.js:535:7) at port.onmessage (https://echo.jefftk.com/audio-worklet.js:511:14)

**Comment by jeffkaufman** [comment]
Firefox on Linux should support the APIs we need.  Was this a recent version of Firefox?  Does Chrome or Edge on Linux work?
