### ISSUE TITLE
Cannot decode non-contiguous chunks!

### ISSUE THREAD

**Issue by jeffkaufman** [gwillen/solstice-audio-test#28]
```
Error: Cannot decode non-contiguous chunks!
    at AudioDecoder.decode_chunk (https://echo.jefftk.com/app.js:721:13)
    at MessagePort.handle_message (https://echo.jefftk.com/app.js:1222:36)
```

should automatically reconnect if this happens

**Comment by jeffkaufman** [comment]
I don't think this happens anymore, or at least when it does the page automatically corrects
