### ISSUE TITLE
Cannot read property 'sampleRate' of undefined

### ISSUE THREAD

**Issue by jeffkaufman** [gwillen/solstice-audio-test#33]
On pressing start, before any calibration started

```
TypeError: Cannot read property 'sampleRate' of undefined
    at start (https://echo.jefftk.com/app.js:847:33)
    at async HTMLButtonElement.start_stop (https://echo.jefftk.com/app.js:492:5)
```

**Comment by jeffkaufman** [comment]
I don't think this happens anymore
