### ISSUE TITLE
Server can freeze

### ISSUE THREAD

**Issue by jeffkaufman** [gwillen/solstice-audio-test#42]
When I hit the server really hard and stress testing, sometimes the Python program becomes unresponsive

**Comment by jeffkaufman** [comment]
When this happens nginx logs look like:

```
2020/11/08 01:29:00 [error] 5850#5850: *1363762 upstream timed out (110: Connection timed out) while connecting to upstream, client: 146.115.48.13, server: echo.jefftk.com, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:8081/", host: "echo.jefftk.com", referrer: "https://echo.jefftk.com/"
```

**Comment by jeffkaufman** [comment]
I tried tracing, and if I'm reading it right it's stuck in `recvfrom`:

```
# strace -p 16531
strace: Process 16531 attached
recvfrom(5,
```

**Comment by jeffkaufman** [comment]
I decided to kill it to get a backtrace:

```
Traceback (most recent call last):
  File "./server.py", line 661, in <module>
    start()
  File "./server.py", line 77, in start
    start_server()
  File "./server.py", line 81, in start_server
    server.serve_forever()
  File "/usr/lib/python3.6/socketserver.py", line 241, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/http/server.py", line 386, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

**Comment by jeffkaufman** [comment]
I wonder if this means it's trying to read from a client that has gone away or something?

**Comment by jeffkaufman** [comment]
I'm going to try uwsgi instead; no reason to have python handling HTTP directly

**Comment by jeffkaufman** [comment]
Since switching to UWSGI I haven't seen this anymore
