### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by darkruby501** [gwillen/solstice-audio-test#60]
TypeError: Failed to construct 'MediaStreamAudioSourceNode': required member mediaStream is undefined.
TypeError: Failed to construct 'MediaStreamAudioSourceNode': required member mediaStream is undefined.
    at EventTarget.start_bucket (https://echo.jefftk.com/app.js:562:20)
    at start (https://echo.jefftk.com/demo.js:940:20)
    at async HTMLButtonElement.start_stop (https://echo.jefftk.com/demo.js:483:5)

**Comment by jeffkaufman** [comment]
I believe this happens when the microphone permissions are not granted. We have since added some thing to detect that situation and say how to fix it.
